Prefix/Suffix Matches Lifecycle Condition
googleapis/java-storage pull request #1389
Opened 2022-05-13 19:30 UTC by sydney-munro

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/java-storage/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #1345 ☕️

If you write sample code, please follow the [samples format](
https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/SAMPLE_FORMAT.md).

2022-05-16 17:57 UTC, BenWhitehead requested changes

2022-05-16 17:57 UTC, BenWhitehead commented on google-cloud-storage/src/main/java/com/google/cloud/storage/BucketInfo.java
> +          this.matchesPrefix = matchesPrefix;
For these setter methods, we'll want to guard the values passed in to be immutable values.
```suggestion
          this.matchesPrefix = matchesPrefix != null ? ImmutableList.copyOf(matchesPrefix) : null;
```

2022-05-16 18:50 UTC, BenWhitehead approved these changes

2022-05-18 17:01 UTC, shaffeeullah approved these changes

2022-06-07 21:06 UTC, merged