feat: Grpc compose
googleapis/java-storage pull request #1498
Opened 2022-07-08 22:51 UTC by sydney-munro

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/java-storage/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> ☕️

If you write sample code, please follow the [samples format](
https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/SAMPLE_FORMAT.md).

2022-07-11 20:29 UTC, sydney-munro commented on google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
> +    for (ComposeRequest.SourceBlob sourceBlob : composeRequest.getSourceBlobs()) {
Concern here:
ComposeRequest does not have options for the source object, yet the ComposeObjectRequest has a field for ObjectPrecondition that apply to the source, the only condition listed is if_generation_match.

2022-07-11 20:30 UTC, sydney-munro commented on google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
> +          SourceObject.newBuilder()
I did not think this was worth writing a codec but could be convinced otherwise.

2022-07-12 16:09 UTC, BenWhitehead requested changes

2022-07-12 16:09 UTC, BenWhitehead commented on google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
> +        composeObjectReqBuilder::setKmsKey);
I think we also need to account for encryption options here, similar to https://github.com/googleapis/java-storage/blob/dc78526343c30ea85fd05c6977696309d687d958/google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java#L1181-L1184

2022-07-12 16:09 UTC, BenWhitehead commented on google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
>    public Blob compose(ComposeRequest composeRequest) {
Can you also update the annotation in Storage.java to include `Transport.GRPC` in the supported transports for compose? https://github.com/googleapis/java-storage/blob/dc78526343c30ea85fd05c6977696309d687d958/google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java#L2499

2022-07-12 22:38 UTC, sydney-munro commented on google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageImpl.java
> +    for (ComposeRequest.SourceBlob sourceBlob : composeRequest.getSourceBlobs()) {
works for me 👍

2022-07-13 18:13 UTC, BenWhitehead approved these changes

2022-07-13 18:13 UTC, merged