samples: adding preconditions to some of the samples
googleapis/java-storage pull request #1718
Opened 2022-10-18 20:55 UTC by sydney-munro

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/java-storage/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> ☕️

If you write sample code, please follow the [samples format](
https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/SAMPLE_FORMAT.md).

2022-10-19 18:16 UTC, BenWhitehead requested changes

2022-10-19 18:16 UTC, BenWhitehead commented on samples/snippets/src/main/java/com/example/storage/object/ReleaseEventBasedHold.java
> +    Blob blob = storage.get(bucketName, objectName);
Can we expand this to keep blobId and storage.get on separate lines, followed by checking that blob is non-null?

I think it's good to keep the simple `BlobId.of` separate from `storage.get` which performs an RPC to try and be clear about the fact they can be distinct.

2022-10-19 18:16 UTC, BenWhitehead commented on samples/snippets/src/main/java/com/example/storage/object/ReleaseTemporaryHold.java
> +    Blob blob = storage.get(bucketName, objectName);
ditto

2022-10-19 18:16 UTC, BenWhitehead commented on samples/snippets/src/main/java/com/example/storage/object/SetEventBasedHold.java
> +    Blob blob = storage.get(bucketName, objectName);
ditto

2022-10-19 18:16 UTC, BenWhitehead commented on samples/snippets/src/main/java/com/example/storage/object/SetTemporaryHold.java
> +    Blob blob = storage.get(bucketName, objectName);
ditto

2022-10-21 00:00 UTC, BenWhitehead approved these changes

2022-10-21 00:01 UTC, BenWhitehead commented
LGTM, get someone from samples reviewers to give it a once over, then merge away!

2022-10-28 19:55 UTC, kurtisvg approved these changes

2022-10-31 16:31 UTC, merged