feat: Handle generation numbers in BlobId#{to,from}GsUtilUri
googleapis/java-storage pull request #1929
Opened 2023-03-07 19:38 UTC by davidmandle

Fixes #1928  ☕️

2023-03-27 22:12 UTC, davidmandle commented
@JesseLovelace might you be able to take a look at this? Or is there another code owner I can reach out to?

2023-04-04 16:33 UTC, BenWhitehead requested changes
In general I think it looks reasonable. One small request on the code structure before approval.

2023-04-04 16:33 UTC, BenWhitehead commented on google-cloud-storage/src/main/java/com/google/cloud/storage/BlobId.java
> +    return BlobId.of(m.group(1), m.group(2), generationGroup == null ? null : Long.parseLong(generationGroup));
Can we keep each of these argument resolutions on its own line like it was before?

i.e `String bucketName = m.group(1);`

This ensures if we ever get an exception from one of these lines we know which parameter it failed on.

2023-04-04 17:04 UTC, davidmandle commented
Thanks for taking a look!

2023-04-04 18:02 UTC, davidmandle commented
This appears to have been impacted by a test flake: https://github.com/googleapis/java-storage/issues/1748 .... tests may need to be re-run.

2023-04-05 16:09 UTC, davidmandle commented
I believe this is currently blocked on approval of the requested changes.

2023-04-05 16:46 UTC, BenWhitehead commented
Change not impacted by owlbot, merging

2023-04-05 16:47 UTC, merged