feat: Add matchGlob parameter to BlobListOption
googleapis/java-storage pull request #1965
Opened 2023-04-04 02:20 UTC by briantruong777

This is a new feature (b/236167515) where List Objects allows filtering results based on a provided glob pattern.

Currently only the JSON API supports the matchGlob parameter, so using the option with gRPC will throw an exception. gRPC support is planned for later.

2023-04-04 16:26 UTC, BenWhitehead requested changes
One small change to the exception construction.

2023-04-04 16:26 UTC, BenWhitehead commented on google-cloud-storage/src/main/java/com/google/cloud/storage/UnifiedOpts.java
> +      throw new UnsupportedOperationException("Option matchGlob is not supported for gRPC yet.");
We have a helper method to construct an appropriate exception with a pointer on how they can use the method.

```suggestion
      return GrpcStorageImpl.throwHttpJsonOnly(
          com.google.cloud.storage.Storage.BlobListOption.class, "matchGlob(String)");
```

Using this, the exception will have a message of
```
java.lang.UnsupportedOperationException: com.google.cloud.storage.Storage$BlobListOption#matchGlob(String) is only supported for HTTP_JSON transport. Please use StorageOptions.http() to construct a compatible instance.
```

2023-04-04 16:26 UTC, BenWhitehead commented on google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITObjectTest.java
> +                  .inOrder());
Looks great, thank you!

2023-04-04 22:22 UTC, briantruong777 commented
Updated to use `throwHttpJsonOnly()`. PTAL.

2023-04-05 15:54 UTC, BenWhitehead approved these changes

2023-04-05 16:48 UTC, BenWhitehead commented
Change not impacted by owlbot, merging.

2023-04-05 16:48 UTC, merged