feat: Add validation around bytes received vs bytes expected
googleapis/java-storage pull request #2078
Opened 2023-06-20 16:51 UTC by sydney-munro

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/java-storage/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> ☕️

If you write sample code, please follow the [samples format](
https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/SAMPLE_FORMAT.md).

2023-06-20 17:36 UTC, BenWhitehead requested changes

2023-06-20 17:36 UTC, BenWhitehead commented on google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/ChunkedDownloadCallable.java
> +                        + bytesExpected))
p.s. I don't know if that code recommendation will compile, I did it from memory double check before accepting it.

2023-06-20 17:49 UTC, sydney-munro commented on google-cloud-storage/src/main/java/com/google/cloud/storage/transfermanager/ChunkedDownloadCallable.java
> +                        + bytesExpected))
Util is capitalized :) added this to both direct and chunked downloads.

2023-06-21 21:41 UTC, BenWhitehead approved these changes
Pre approving this draft, feel free to merge after un-drafting.

2023-06-21 23:39 UTC, merged