feat: Adds a ZeroCopy response marshaller for grpc ReadObject handling
googleapis/java-storage pull request #2489
Opened 2024-04-04 18:08 UTC by JesseLovelace

Adds a Zero Copy ReadObject marshaller for grpc and some basic tests

2024-04-04 20:33 UTC, BenWhitehead commented on google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageOptions.java
> +        System.out.println(unsafeByteOperationsClassName);
```suggestion
```

2024-04-09 04:01 UTC, BenWhitehead requested changes
Can you purge out the owlbot samples formatting, and readme edits updates? They're adding noise to the PR. Other than that, a few minor things.

2024-04-11 19:45 UTC, frankyn commented on google-cloud-storage/src/main/java/com/google/cloud/storage/GrpcStorageOptions.java
> +                    builder.add(request.getBucket(), "bucket", PathTemplate.create("{bucket=**}"));
File FR against GAPIC for this: https://github.com/googleapis/sdk-platform-java/issues/2501
Could point to this in the mean time?

2024-04-14 23:39 UTC, frankyn approved these changes

2024-04-14 23:42 UTC, merged