docs: Create Samples for transfer manager
googleapis/java-storage pull request #2492
Opened 2024-04-08 17:51 UTC by sydney-munro

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/java-storage/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> ☕️

If you write sample code, please follow the [samples format](
https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/SAMPLE_FORMAT.md).

2024-04-11 17:17 UTC, BenWhitehead requested changes

2024-04-11 17:17 UTC, BenWhitehead commented on samples/snippets/src/main/java/com/example/storage/transfermanager/DownloadBucket.java
> +        .map(blob -> blob.asBlobInfo())
Nit
```suggestion
        .map(Blob::asBlobInfo)
```

2024-04-11 17:17 UTC, BenWhitehead commented on samples/snippets/src/main/java/com/example/storage/transfermanager/UploadDirectory.java
> +  public static void uploadDirectoryContents(String bucketName, Path sourceDirectory)
This needs a test

2024-04-11 17:17 UTC, BenWhitehead commented on samples/snippets/src/main/java/com/example/storage/transfermanager/DownloadBucket.java
> +  public static void downloadBucketContents(String projectId,
This also needs a test

2024-04-11 19:12 UTC, BenWhitehead approved these changes
lgtm from java side, probably want to get andrew to review for the general review.

2024-04-12 19:10 UTC, andrewsg approved these changes
LGTM

2024-04-12 21:08 UTC, merged