feat: Add shouldReturnRawInputStream option to Get requests
googleapis/java-storage pull request #872
Opened 2021-06-09 18:45 UTC by JesseLovelace

Adds support for shouldReturnRawInputStream, which will allow users to specify whether the client should auto-decompress gzipped content or not. 

Note: `read(StorageObject, Map<Option, ?>, long, OutputStream)` and `read(StorageObject, Map<Option, ?>, long, int)` in HttpStorageRpc are set up to have different defaults to preserve their original behavior. Before, returnRawInputStream was always set to true, however `read(StorageObject, Map<Option, ?>, long, OutputStream)` had a bug that would cause that to be lost, so it would always turn out to be false (this is why blob.downloadTo and BlobReadChannel.read had different behaviors). That bug is fixed here, but these method signatures now have different defaults to preserve the original behavior. Users can use the new flag to change that behavior 

Fixes #321

2021-06-09 22:03 UTC, frankyn requested changes

2021-06-14 18:41 UTC, merged

2021-06-15 09:00 UTC, oripwk commented
@JesseLovelace Does it work also with `getContent()` or only with `downloadTo()`?

2021-06-15 20:59 UTC, JesseLovelace commented
@oripwk Should work with `getContent`, use `getContent(Blob.BlobSourceOption.shouldReturnRawInputStream(true));`

2021-06-16 08:19 UTC, oripwk commented
@JesseLovelace when is it going to be released?

2021-06-16 16:23 UTC, oripwk commented
Good, I see it's on 1.116.0

2021-10-20 12:51 UTC, marioaae commented
Hi there, thanks for fixing this, unfortunately I haven't been able to make it work on my end. In Scala I'm trying to read files through a GZIPInputStream as follows:

```
val bucketName       = configuration.get[String]("backup.bucketName")
val filePath                = "path/to/file.gz
val storage: Storage = StorageOptions.getDefaultInstance.getService

val blob: Blob = storage.get(BlobId.of(bucketName, fullPath), Storage.BlobGetOption.shouldReturnRawInputStream(true))
val reader: ReadChannel = blob.reader()
val inputStream: InputStream = Channels.newInputStream(reader)
```

Afterwards I'm wrapping it up in a GZIPInputStream to process it as follows: `new GZIPInputStream(inputStream)` but I get the following error:

`java.util.zip.ZipException: Not in GZIP format`

Still, if I only use the InputStream it works, so it seems to me that the file is being downloaded decompressed, I thought the `shouldReturnRawInputStream(true)` would download my file compressed in the original .gz format.

When I download the file from a different source (e.g. an SFTP server) where I know for sure no decompression is going on, wrapping it up in GZIPInputStream works properly.

Has anybody had the same problem?

Thanks!